title:            Road to CUBA and beyond...
description:      On this blog you'll find information about the CUBA Platform and related stuff
disqus_shortname: roadtocubaandbeyond
reading_time:     true
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://www.road-to-cuba-and-beyond.com

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about'
  - title: 'Tags'
    url: '/tags'


# Owner/author information
owner:
  name:           Mario David
  site:           http://road-to-cuba-and-beyond.com
  avatar:         images/avatar.jpg
  bio:            "Software developer with passion on agile, web and fast development, blogger, father, family guy"
  email:          mario@die-davids.de
  # Social networking links used in footer. Update and remove as you like.
  twitter: mariomddavid
  github: mariodavid
  stackexchange: mariodavid

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: 

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-70081127-1
google_verify: mpQ9xZAZnbNyl04qI70Di7vIxlbRd18S1iSOYInz89Q
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Germany/Berlin
locale:      de_DE
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

gems: [jekyll-paginate]
